In [6]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

In [7]:
p = pd.read_csv("phishing.csv") 

In [10]:
p.info()
print(type(p))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11054 entries, 0 to 11053
Data columns (total 31 columns):
-1       11054 non-null int64
1        11054 non-null int64
1.1      11054 non-null int64
1.2      11054 non-null int64
-1.1     11054 non-null int64
-1.2     11054 non-null int64
-1.3     11054 non-null int64
-1.4     11054 non-null int64
-1.5     11054 non-null int64
1.3      11054 non-null int64
1.4      11054 non-null int64
-1.6     11054 non-null int64
1.5      11054 non-null int64
-1.7     11054 non-null int64
1.6      11054 non-null int64
-1.8     11054 non-null int64
-1.9     11054 non-null int64
-1.10    11054 non-null int64
0        11054 non-null int64
1.7      11054 non-null int64
1.8      11054 non-null int64
1.9      11054 non-null int64
1.10     11054 non-null int64
-1.11    11054 non-null int64
-1.12    11054 non-null int64
-1.13    11054 non-null int64
-1.14    11054 non-null int64
1.11     11054 non-null int64
1.12     11054 non-null int64
-1.15    11054 non-nu

In [17]:
p.columns = ['having_IPhaving_IP_Address',
'URLURL_Length',
'Shortining_Service',
'having_At_Symbol',
'double_slash_redirecting',
'Prefix_Suffix',
'having_Sub_Domain',
'SSLfinal_State',
'Domain_registeration_length',
'Favicon',
'port',
'HTTPS_token',
'Request_URL',
'URL_of_Anchor',
'Links_in_tags',
'SFH',
'Submitting_to_email',
'Abnormal_URL',
'Redirect',
'on_mouseover',
'RightClick',
'popUpWidnow',
'Iframe',
'age_of_domain',
'DNSRecord',
'web_traffic',
'Page_Rank',
'Google_Index',
'Links_pointing_to_page',
'Statistical_report',
'Result']
target = p["Result"].T

data = p.drop('Result', axis = 1).values


print(data)
print(target)


[[ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 [ 1  0  1 ...  1 -1  1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]]
0       -1
1       -1
2       -1
3        1
4        1
5       -1
6       -1
7        1
8       -1
9        1
10      -1
11      -1
12      -1
13       1
14      -1
15      -1
16      -1
17       1
18       1
19       1
20       1
21       1
22       1
23       1
24       1
25      -1
26       1
27       1
28       1
29       1
        ..
11024    1
11025    1
11026    1
11027    1
11028   -1
11029   -1
11030    1
11031   -1
11032    1
11033   -1
11034    1
11035    1
11036   -1
11037   -1
11038   -1
11039   -1
11040    1
11041    1
11042   -1
11043    1
11044    1
11045    1
11046   -1
11047    1
11048   -1
11049    1
11050   -1
11051   -1
11052   -1
11053   -1
Name: Result, Length: 11054, dtype: int64


In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test =train_test_split(data, target, test_size=0.3,random_state=21, stratify=target)

In [24]:
knn = KNeighborsClassifier(n_neighbors = 5)

In [33]:
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))
print("accuracy: ",knn.score(X_test, y_test))

Test set predictions:
 [ 1 -1 -1 ... -1 -1  1]
accuracy:  0.9529695507989147


In [35]:
len(X_test)

3317

In [45]:
y_test = np.asarray(y_test)
X_test = np.asarray(X_test)
misclassified = np.where(y_test != X_test)
print(misclassified)

(array([0]),)


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until
