# Numpy

In [14]:
fixed_salary = [100,200,300]
variable_salary = [10,20,30]
total_salary = fixed_salary + variable_salary
print(total_salary)

[100, 200, 300, 10, 20, 30]


In [15]:
type(fixed_salary)

list

In [16]:
import numpy as np
fixed = np.array(fixed_salary)
variable = np.array(variable_salary)
total = fixed + variable
print(total)

[110 220 330]


In [8]:
type(fixed)

numpy.ndarray

In [9]:
fixed

array([100, 200, 300])

In [10]:
variable

array([10, 20, 30])

In [18]:
type(total)

numpy.ndarray

In [18]:
total

array([110, 220, 330])

In [9]:
#Broadcasting
total+10

array([120, 230, 340])

In [11]:
#Broadcasting
total>200

array([False,  True,  True])

In [7]:
#Boolean Indexing
total[total%2==0]

array([110, 220, 330])

In [17]:
total[total>200][1]

330

Numpy is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.
First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.
Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [5]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [6]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)
print(np_baseball)

<class 'numpy.ndarray'>
(4, 2)
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [7]:
print(np_baseball[1][0])
print(np_baseball[1,0])

215.0
215.0


In [21]:
#Upcasting:

In [22]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [23]:
#two dimensions

In [24]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [33]:
print("A series of numbers:",np.arange(5,16)) # A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [34]:
print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [10]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,10))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [36]:
import numpy as np
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


# Matrix creation

In [37]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [38]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [40]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [41]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [42]:
#Return numbers spaced evenly on a log scale.

In [43]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [44]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [45]:
x = np.arange(9).reshape((3,3))

In [46]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
np.diag(x)

array([0, 4, 8])

# Reshaping

In [11]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


In [49]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [50]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [14 96 85 35 94 26 17 18  6 83 24 54 31 40 98  6 99 95 62 25  1 60 77 87
 18 26 37 90 86 77] 
 --------------------

b looks like
 -------------------- 
 [[[14 96 85 35 94]
  [26 17 18  6 83]
  [24 54 31 40 98]]

 [[ 6 99 95 62 25]
  [ 1 60 77 87 18]
  [26 37 90 86 77]]] 
 --------------------

c looks like
 -------------------- 
 [[14 96 85 35 94]
 [26 17 18  6 83]
 [24 54 31 40 98]
 [ 6 99 95 62 25]
 [ 1 60 77 87 18]
 [26 37 90 86 77]] 
 --------------------


In [51]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of random integers
 -------------------------------------------------- 
 [39  6  1 32 45 81 73 42 41  1]

Here is the sorted vector
 -------------------------------------------------- 
 [ 1  1  6 32 39 41 42 45 73 81]


In [52]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[71 68 30 23 40]
 [49 76 11 83 22]
 [68 15 68  5 66]
 [69 28 64 89 36]
 [51 46 23 44 14]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[23 30 40 68 71]
 [11 22 49 76 83]
 [ 5 15 66 68 68]
 [28 36 64 69 89]
 [14 23 44 46 51]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[49 15 11  5 14]
 [51 28 23 23 22]
 [68 46 30 44 36]
 [69 68 64 83 40]
 [71 76 68 89 66]]


In [53]:
print("Max of a:", a.max())
print("Max of b:", b.max())


Max of a: 99
Max of b: 99


In [54]:
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: 16
Max of b location: 16
Max of c location: 16


# Indexing and slicing

In [13]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [56]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [57]:
print("Elements from 3rd to 5th index are:", arr[3:6])


Elements from 3rd to 5th index are: [3 4 5]


In [58]:
print("Elements up to 4th index are:", arr[:4])


Elements up to 4th index are: [0 1 2 3]


In [59]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [60]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [61]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[71 47 60 73 47]
 [49 25 81 92 49]
 [42 45 44 87 68]]


In [62]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])



Double bracket indexing
------------------------
Element in row index 1 and column index 2: 81


In [63]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 81

Row or column extract
----------------------


In [64]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [42 45 44 87 68]
Entire column at index 3: [73 92 87]


In [65]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[92 49]
 [87 68]]


In [66]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[47 73]
 [25 92]]


# Subseting

In [67]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


Matrix of random 2-digit numbers
--------------------------------
 [[91 70 12 80 10]
 [54 87 65 81 27]
 [60 15 57 79 63]]


In [68]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [91 70 80 54 87 65 81 60 57 79 63]


# Slicing

In [69]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [70]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [71]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


# Universal Functions

In [72]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[7 7 4]
 [5 8 2]
 [3 6 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 1 4]
 [3 4 9]
 [5 2 3]]


In [73]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)



Addition
------------------
 [[13  8  8]
 [ 8 12 11]
 [ 8  8  7]]

Multiplication
------------------
 [[42  7 16]
 [15 32 18]
 [15 12 12]]


In [74]:
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[1.16666667 7.         1.        ]
 [1.66666667 2.         0.22222222]
 [0.6        3.         1.33333333]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[  9  19   4]
 [  9  16 -12]
 [ -1  14   6]]


In [75]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[107 107 104]
 [105 108 102]
 [103 106 104]]


In [76]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


Exponentiation, matrix cubed here
----------------------------------------
 [[343 343  64]
 [125 512   8]
 [ 27 216  64]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[2.64575131 2.64575131 2.        ]
 [2.23606798 2.82842712 1.41421356]
 [1.73205081 2.44948974 2.        ]]


# Array Math

In [77]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[5 3 9]
 [1 5 2]
 [8 3 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 2 1]
 [9 1 9]
 [7 4 1]]


In [78]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.23606798 1.73205081 3.        ]
 [1.         2.23606798 1.41421356]
 [2.82842712 1.73205081 2.82842712]]


In [79]:
#Exponential with e (2.71)
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 2.00855369e+01 8.10308393e+03]
 [2.71828183e+00 1.48413159e+02 7.38905610e+00]
 [2.98095799e+03 2.00855369e+01 2.98095799e+03]]


In [80]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))



10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.47712125 0.95424251]
 [0.         0.69897    0.30103   ]
 [0.90308999 0.47712125 0.90308999]]


# basic stats

In [15]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 2 7]
 [3 2 3]
 [3 5 6]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 7 5]
 [8 5 8]
 [4 5 1]]


In [18]:
print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))



Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 38

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [13  9 16]


In [17]:
print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))



Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [16  8 14]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [98 18 90]


In [84]:
print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))



Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [21 70 36]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.666666666666667


In [85]:
print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))



Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2.309401076758503


In [86]:
print("\n Variance of all numbers in 1st matrix\n","-"*50,"\n",np.var(mat1))



 Variance of all numbers in 1st matrix
 -------------------------------------------------- 
 5.333333333333333


In [87]:
print("\n50th percentile of all numbers in the modified matrix\n","-"*60,"\n",np.percentile(mat1,50))



50th percentile of all numbers in the modified matrix
 ------------------------------------------------------------ 
 5.0


In [88]:
print("\n90th percentile of all numbers in the modified matrix\n","-"*60,"\n",np.percentile(mat1,90))


90th percentile of all numbers in the modified matrix
 ------------------------------------------------------------ 
 7.4


In [89]:
print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



Median of all numbers in the modified matrix
 ------------------------------------------------------------ 
 5.0


In [20]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False  True False  True]
[False False False  True]


In [21]:
my_house[(my_house > 18.5) | (my_house < 10)]

array([20. ,  9.5])

In [105]:
(my_house < 11) & (your_house < 11)

array([False, False, False,  True])

In [6]:
np_baseball = np.array([[ 74, 180],[ 74, 215],[ 72, 210],[ 75, 205],[ 75, 190],[ 73, 195]])
np_height = np.array([74, 74, 72, 75, 75, 73])

In [7]:
for x in np_baseball:
    print(x)

[ 74 180]
[ 74 215]
[ 72 210]
[ 75 205]
[ 75 190]
[ 73 195]


In [8]:
# Import numpy as np
import numpy as np

# For loop over np_height
for x in np_height:
    print(str(x) + " inches")

# For loop over np_baseball
for x in np.nditer(np_baseball):
    print(str(x))


74 inches
74 inches
72 inches
75 inches
75 inches
73 inches
74
180
74
215
72
210
75
205
75
190
73
195


## Pandas

In [9]:
import pandas as pd

# Build cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
dict = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(dict)
print(cars)

# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
print(cars)

   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True
     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True


In [10]:
#Renamed
cars.columns = ['Cars Per Capita','Country Name','Drives Right']
cars

Cars Per Capita   Country Name  Drives Right
US               809  United States          True
AUS              731      Australia         False
JAP              588          Japan         False
IN                18          India         False
RU               200         Russia          True
MOR               70        Morocco          True
EG                45          Egypt          True

In [11]:
#Building DataFrames with broadcasting

# Make a string with the value 'PA': state
planet = 'Earth'
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
# Construct a dictionary: data
data = {'Country':names, 'Planet':planet}

# Construct a DataFrame from dictionary data: df
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

         Country Planet
0  United States  Earth
1      Australia  Earth
2          Japan  Earth
3          India  Earth
4         Russia  Earth
5        Morocco  Earth
6          Egypt  Earth


In [23]:
import pandas as pd

# Build cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
dict = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(dict)
print(cars)

# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
print(cars)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45
           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JAP          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45


In [32]:
# Print out country column as Pandas Series
cars['country']

US     United States
AUS        Australia
JAP            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object

In [37]:
cars[['country','drives_right']]

country  drives_right
US   United States          True
AUS      Australia         False
JAP          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True

In [39]:
# Print out DataFrame with country and drives_right columns
cars[['country', 'drives_right']]

country  drives_right
US   United States          True
AUS      Australia         False
JAP          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True

In [28]:
# Print out first 3 observations
print(cars[0:3])

# Print out fourth, fifth and sixth observation
print(cars[3:6])

           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JAP          Japan         False           588
     country  drives_right  cars_per_cap
IN     India         False            18
RU    Russia          True           200
MOR  Morocco          True            70


In [17]:
# Print out observation for Japan
print(cars.iloc[2])

# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
     cars_per_cap    country  drives_right
AUS           731  Australia         False
EG             45      Egypt          True


In [18]:
# Print out drives_right value of Morocco
print(cars.iloc[5, 2])

# Print sub-DataFrame
print(cars.loc[['RU', 'MOR'], ['country', 'drives_right']])

True
     country  drives_right
RU    Russia          True
MOR  Morocco          True


In [19]:
# Print out drives_right column as Series
print(cars.iloc[:, 2])

# Print out drives_right column as DataFrame
print(cars.iloc[:, [2]])

# Print out cars_per_cap and drives_right as DataFrame
print(cars.loc[:, ['cars_per_cap', 'drives_right']])

US      True
AUS    False
JAP    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool
     drives_right
US           True
AUS         False
JAP         False
IN          False
RU           True
MOR          True
EG           True
     cars_per_cap  drives_right
US            809          True
AUS           731         False
JAP           588         False
IN             18         False
RU            200          True
MOR            70          True
EG             45          True


In [20]:
# Import numpy, you'll need this
import numpy as np

# Create medium: observations with cars_per_cap between 100 and 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Print medium
medium

cars_per_cap country  drives_right
RU           200  Russia          True

In [21]:
cpc > 100

US      True
AUS     True
JAP     True
IN     False
RU      True
MOR    False
EG     False
Name: cars_per_cap, dtype: bool

In [22]:
cpc < 500

US     False
AUS    False
JAP    False
IN      True
RU      True
MOR     True
EG      True
Name: cars_per_cap, dtype: bool

In [23]:
np.logical_and(cpc > 100, cpc < 500)

US     False
AUS    False
JAP    False
IN     False
RU      True
MOR    False
EG     False
Name: cars_per_cap, dtype: bool

In [27]:
# Iterate over rows of cars
for lab, row in cars.iterrows() :
    print(lab)
    print(row)

US
cars_per_cap              809
country         United States
drives_right             True
COUNTRY         UNITED STATES
name_length                13
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
COUNTRY         AUSTRALIA
name_length             9
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
COUNTRY         JAPAN
name_length         5
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
COUNTRY         INDIA
name_length         5
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
COUNTRY         RUSSIA
name_length          6
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
COUNTRY         MOROCCO
name_length           7
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
COUNTRY         EGYPT
name_l

In [28]:
# Adapt for loop
for lab, row in cars.iterrows() :
    print(lab + ": " + str(row['cars_per_cap']))

US: 809
AUS: 731
JAP: 588
IN: 18
RU: 200
MOR: 70
EG: 45


In [29]:
# Code for loop that adds COUNTRY column
for lab, row in cars.iterrows() :
    cars.loc[lab, "COUNTRY"] = row["country"].upper()
    
# Print cars
print(cars)

     cars_per_cap        country  drives_right        COUNTRY  name_length
US            809  United States          True  UNITED STATES           13
AUS           731      Australia         False      AUSTRALIA            9
JAP           588          Japan         False          JAPAN            5
IN             18          India         False          INDIA            5
RU            200         Russia          True         RUSSIA            6
MOR            70        Morocco          True        MOROCCO            7
EG             45          Egypt          True          EGYPT            5


In [30]:
# Use .apply(str.upper)
cars["COUNTRY"] = cars["country"].apply(str.upper)

In [31]:
cars["name_length"] = cars["country"].apply(len)